FROM node:10.16.0-alpine
RUN mkdir -p /app/config /app/src
WORKDIR /app
COPY package.json /app/package.json
COPY docker.env /app/.env
COPY package-lock.json /app/package-lock.json
RUN npm install
CMD ["npm", "run", "dev"]